import { systemToolPath } from './system-tools.js';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join, relative, sep } from 'node:path';
import { resolveCoredocHome } from '@coredoc/core/utils';
import { outsideSource } from './isolated-process.js';

export interface PinnedTool {
  name: string;
  version: string;
  url: string;
  sha256: string;
  entry: string;
  /** An npm archive ships a ready-to-run bundle; no install scripts or dependency resolution. */
  archive?: { prefix: string; contentsSha256: string };
}

export interface ToolInstallOptions {
  signal?: AbortSignal;
  onLog?: (message: string) => void;
  onProgress?: (received: number, total?: number) => void;
}

function directory(tool: PinnedTool, repoRoot?: string): string {
  const path = join(resolveCoredocHome(), 'tools', tool.name, tool.version);
  return repoRoot ? outsideSource(repoRoot, path) : path;
}

export function toolContentsHash(directory: string): string {
  const hash = createHash('sha256');
  const files = readdirSync(directory, { recursive: true, withFileTypes: true })
    .flatMap((entry) => {
      if (entry.isSymbolicLink()) throw new Error('Installed tools must not contain symbolic links.');
      return entry.isFile() ? [relative(directory, join(entry.parentPath, entry.name)).split(sep).join('/')] : [];
    })
    .sort();
  for (const file of files)
    hash
      .update(file)
      .update('\0')
      .update(readFileSync(join(directory, file)))
      .update('\0');
  return hash.digest('hex');
}

/** Validate executable bytes on reuse, not a marker generated by an earlier install. */
export function installedTool(tool: PinnedTool, repoRoot?: string): string | undefined {
  const target = directory(tool, repoRoot);
  try {
    if (lstatSync(target).isSymbolicLink()) return undefined;
    const entry = join(target, tool.entry);
    if (!lstatSync(entry).isFile() || lstatSync(entry).isSymbolicLink()) return undefined;
    const valid = tool.archive
      ? toolContentsHash(target) === tool.archive.contentsSha256
      : createHash('sha256').update(readFileSync(entry)).digest('hex') === tool.sha256;
    return valid ? entry : undefined;
  } catch {
    return undefined;
  }
}

/** Only explicit CLI/UI installation invokes this; parse/discovery never downloads tools. */
export async function installTool(
  tool: PinnedTool,
  repoRoot?: string,
  options: ToolInstallOptions = {},
): Promise<string> {
  options.signal?.throwIfAborted();
  const existing = installedTool(tool, repoRoot);
  if (existing) return existing;
  const target = directory(tool, repoRoot);
  mkdirSync(join(target, '..'), { recursive: true });
  const work = mkdtempSync(join(target, '..', 'install-'));
  try {
    options.onLog?.(`Downloading ${tool.name} ${tool.version}…`);
    const signal = options.signal
      ? AbortSignal.any([options.signal, AbortSignal.timeout(120_000)])
      : AbortSignal.timeout(120_000);
    const response = await fetch(tool.url, { signal }).catch((error) => {
      options.signal?.throwIfAborted();
      const reason = error?.cause?.code ?? error?.cause?.message ?? error?.message ?? 'connection failed';
      throw new Error(
        `Cannot download ${tool.name} from ${new URL(tool.url).hostname}: ${reason}. Check your connection and retry, or choose basic analysis.`,
        { cause: error },
      );
    });
    if (!response.ok || !response.body) throw new Error(`Tool download failed (HTTP ${response.status}).`);
    const chunks: Uint8Array[] = [];
    const total = Number(response.headers.get('content-length')) || undefined;
    let size = 0;
    let lastUpdate = 0;
    options.onProgress?.(0, total);
    for await (const chunk of response.body) {
      size += chunk.length;
      if (size > 64 * 1024 * 1024) throw new Error('Tool download exceeds the expected size.');
      chunks.push(chunk);
      if (Date.now() - lastUpdate >= 250) {
        options.onProgress?.(size, total);
        lastUpdate = Date.now();
      }
    }
    options.onProgress?.(size, total);
    const bytes = Buffer.concat(chunks);
    if (createHash('sha256').update(bytes).digest('hex') !== tool.sha256)
      throw new Error('Tool checksum verification failed.');
    options.signal?.throwIfAborted();
    const unpacked = join(work, 'unpacked');
    mkdirSync(unpacked);
    let ready = unpacked;
    if (tool.archive) {
      const archive = join(work, 'tool.tgz');
      writeFileSync(archive, bytes);
      // Only a pinned, verified archive reaches tar; contents are checked again after extraction.
      const systemBin =
        process.platform === 'win32' ? join(process.env.SystemRoot ?? 'C:\\Windows', 'System32') : '/usr/bin';
      execFileSync(systemToolPath('tar'), ['-xzf', archive, '-C', unpacked], {
        timeout: 30_000,
        stdio: 'pipe',
        cwd: work,
        // GNU tar launches gzip through PATH; never execute a repository's decompressor.
        env: { PATH: process.platform === 'win32' ? systemBin : '/usr/bin:/bin', LANG: 'C', LC_ALL: 'C' },
      });
      ready = join(unpacked, tool.archive.prefix);
      if (toolContentsHash(ready) !== tool.archive.contentsSha256)
        throw new Error('Extracted tool contents do not match the pinned release.');
    } else {
      writeFileSync(join(ready, tool.entry), bytes);
      chmodSync(join(ready, tool.entry), 0o755);
    }
    options.signal?.throwIfAborted();
    if (existsSync(target) && !installedTool(tool, repoRoot)) rmSync(target, { recursive: true, force: true });
    try {
      renameSync(ready, target);
    } catch (error) {
      if (!installedTool(tool, repoRoot)) throw error;
    }
    options.onLog?.(`Installed ${tool.name} ${tool.version}.`);
    return join(target, tool.entry);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}
