/**
 * Summary Types for Function Summaries
 *
 * These types define the schema for AI-generated function summaries,
 * used for code understanding and retrieval.
 */

export type ConfidenceLevel = 'high' | 'medium' | 'low';

export type SideEffectType = 'logging' | 'database' | 'event' | 'external_call' | 'job' | 'other';

/**
 * A side effect performed by a function
 */
export interface SideEffect {
  /** Category of side effect */
  type: SideEffectType;
  /** Description of what the side effect does */
  description: string;
  /** Whether this is a direct effect (in this function's code) vs propagated from callee */
  isDirect: boolean;
}

/**
 * Individual function summary generated by AI
 */
export interface FunctionSummary {
  /** Stable ID of the function */
  functionId: string;

  /** Versioned ID for cache invalidation */
  versionedId: string;

  /** Detailed description of what the function does */
  detailed_summary: string;

  /** One-sentence intent/purpose */
  purpose: string;

  /**
   * Business logic rules extracted from the code:
   * - Filters and conditions
   * - if/else branching logic
   * - Validation rules
   * - Switch/case patterns
   */
  business_logic: string[];

  /**
   * Direct side effects only (not propagated from callees):
   * - logging: console/logger calls
   * - database: DB read/write operations
   * - event: event emissions (Kafka, EventEmitter, etc.)
   * - external_call: HTTP/gRPC calls to other services
   * - job: job scheduling/queuing
   * - other: other side effects
   */
  side_effects: SideEffect[];

  /** How data is transformed, validated, or processed */
  data_handling: string;

  /** Confidence in the accuracy of this summary */
  confidence_level: ConfidenceLevel;

  /** Notes about things that couldn't be determined from the code */
  unknowns: string[];

  /** ISO timestamp when summary was generated */
  generatedAt: string;
}

/**
 * Statistics about the summarization run
 */
export interface SummaryStats {
  /** Total functions in the repo */
  totalFunctions: number;
  /** Functions summarized in this run */
  summarized: number;
  /** Functions skipped due to cache hit */
  skippedCached: number;
  /** Functions that failed summarization */
  failedSummarization: number;
  /** Total processing time in milliseconds */
  processingTimeMs: number;
}

/**
 * Repository-level summary generated by AI
 */
export interface RepositorySummary {
  /** High-level overview (2-3 sentences) */
  overview: string;
  /** Brief description of main data entities and relationships */
  dataModel: string;
  /** List of external services/integrations */
  externalIntegrations: string[];
  /** ISO timestamp */
  generatedAt: string;
}

/**
 * Output file schema: {repoName}-summaries.json
 */
export interface SummaryOutput {
  /** Repo stable ID */
  repoId: string;

  /** Repo name */
  repoName: string;

  /** ISO timestamp of when summaries were generated/updated */
  generatedAt: string;

  /** Summarizer version for schema migrations */
  summarizerVersion: string;

  /** All function summaries */
  summaries: FunctionSummary[];

  /** Statistics from the summarization run */
  stats: SummaryStats;

  /** Repository-level summary (optional, generated with --repo-summary flag) */
  repositorySummary?: RepositorySummary;

  /** Package-level summaries (optional, generated with --repo-summary flag for monorepos) */
  packageSummaries?: Array<{ packageId: string; purpose: string; generatedAt: string }>;
}

/**
 * Context about a callee function passed to the summarizer
 * Used to provide context without propagating side effects
 */
export interface CalleeSummaryContext {
  /** Function stable ID */
  functionId: string;
  /** Function name for display */
  functionName: string;
  /** One-sentence purpose (for context) */
  purpose: string;
  /** Side effects (marked as indirect, for awareness only) */
  side_effects: SideEffect[];
}

/**
 * Result of parsing AI response
 */
export interface ParsedAISummary {
  detailed_summary: string;
  purpose: string;
  business_logic: string[];
  side_effects: Array<{
    type: string;
    description: string;
    isDirect: boolean;
  }>;
  data_handling: string;
  confidence_level: string;
  unknowns: string[];
}
