/**
 * Declarative sdkMapping fallback — the moniker-independent recovery tier for
 * SDK-mediated cross-repo calls the SCIP symbol hop cannot reach.
 *
 * Why this exists:
 * The symbol hop joins a consumer call onto an SDK method node by SCIP moniker.
 * It CANNOT fire for two dominant cases:
 *   1. A client class defined LOCALLY in the consumer repo (a `local:` moniker,
 *      no package moniker) — there is no cross-repo join key.
 *   2. A consumer whose `node_modules` lack the SDK package — SCIP cannot trace
 *      the cross-package call chain, so no moniker is decoded at all.
 * Both are SDK-mediated egress calls that resolve correctly when the SDK
 * (class/package, method) → route is known declaratively.
 *
 * The fallback is data-driven: routes come from `override.sdkMappings` rows
 * `{ sdkPackage, sdkClass, sdkMethod, targetService, http:{ method, pathTemplate } }`
 * (the existing mapper-schema shape — autogenerated from in-workspace SDK repos,
 * never hand-curated client names in code). It synthesizes the SDK method's route
 * as an `ExternalCallTarget`, which the EXISTING protocol hop then matches to a
 * target entrypoint. So the fallback only supplies the missing (class, method) →
 * route step; the protocol hop is reused unchanged.
 *
 * Tiering (chain-walker): the symbol hop runs first and wins when it fires; this
 * fallback fills only the calls the symbol hop misses. It is never consulted when
 * the symbol hop or a direct protocol hop already resolved.
 */

import type { ExternalCallTarget } from '../types/output.js';
import type { ExternalCallLike } from './descriptor-matcher.js';
import type { SdkMapping } from './mapper-schema.js';

/** Normalize an SDK class/package/method token for case-insensitive joining. */
function norm(token: string): string {
  return token.trim().toLowerCase();
}

/**
 * Strip a `local:` (or any `<scheme>:`) prefix off an SDK identity token before
 * joining. A locally-defined client surfaces as `sdkName: 'local:SampleApiClient'`
 * on the parsed call but the mapper row stores the bare class name `SampleApiClient`;
 * keying on the prefix-stripped form lets both sides meet.
 */
function stripScheme(token: string): string {
  const colon = token.indexOf(':');
  return colon === -1 ? token : token.slice(colon + 1);
}

/**
 * Index over the declared sdkMappings, queried in three precision tiers:
 *
 *   1. `class::method`   — the call's SDK identity matches a row's `sdkClass`.
 *                          Registered ONLY when every row under that (class, method)
 *                          declares the SAME route: this is the tier `lookup` tries
 *                          first, so an order-dependent answer here would decide the
 *                          whole lookup. A class whose method maps to ≥2 distinct
 *                          routes registers no key and falls through to tier 2.
 *   2. `package::method` — the call's SDK identity (or moniker package) matches a
 *                          row's `sdkPackage`. Registered ONLY when every row under
 *                          that (package, method) declares the SAME route — a package
 *                          whose method name maps to ≥2 distinct routes registers no
 *                          key, mirroring the moniker structural index's refusal of
 *                          ambiguous (package, method) keys.
 *   3. `method`-only     — a last-resort tier that fires ONLY when the method name
 *                          maps to exactly ONE route across the WHOLE table (no
 *                          ambiguity). This is what recovers locally-defined clients
 *                          whose `sdkName` is a repo-local module path (e.g.
 *                          `app/lib/sample-api-client`) that matches neither the
 *                          class nor the package — the dominant `local:` case. A
 *                          method whose name appears under ≥2 distinct
 *                          routes registers NO method-only key, so the tier stays
 *                          conservative rather than mis-hitting (mirrors the symbol
 *                          hop's structural-fallback discipline).
 *
 * All key parts are normalized (trimmed, lower-cased, `<scheme>:` prefix stripped).
 */
export interface SdkMappingIndex {
  /** Resolve a call's (sdk identity, method) to its declared route, or undefined. */
  lookup(call: ExternalCallLike): SdkMapping | undefined;
}

export function buildSdkMappingIndex(rows: readonly SdkMapping[]): SdkMappingIndex {
  const byKey = new Map<string, SdkMapping>();
  const classKey = (klass: string, method: string) => `c|${norm(stripScheme(klass))}|${norm(method)}`;
  const pkgKey = (pkg: string, method: string) => `p|${norm(pkg)}|${norm(method)}`;
  const methodKey = (method: string) => `m|${norm(method)}`;

  // Ambiguity discipline for ALL THREE tiers: a key registers only when every row
  // sharing it agrees on one route signature. The moniker structural index refuses
  // ambiguous (package, method) keys the same way, so an unguarded tier here would
  // silently trump that honest refusal at higher confidence. The class tier is gated
  // too — it is the tier `lookup` tries FIRST, so last-write-wins there made the
  // highest-precedence answer depend on row order in the mapper file.
  const routesByKey = new Map<string, Set<string>>();
  const rowByKey = new Map<string, SdkMapping>();
  const routeSig = (r: SdkMapping) => `${norm(r.targetService)}|${r.http!.method}|${r.http!.pathTemplate}`;
  // Row identity, so that among equal-route rows the retained one does not depend on
  // input order (the index must be a pure function of the row SET).
  const rowId = (r: SdkMapping) => `${norm(r.sdkPackage)}|${norm(r.sdkClass)}|${norm(r.sdkMethod)}`;

  for (const row of rows) {
    // Only rows that carry a concrete route are useful to the fallback — a row with
    // no `http` cannot synthesize a descriptor for the protocol hop.
    if (!row.http) continue;
    for (const key of [
      classKey(row.sdkClass, row.sdkMethod),
      pkgKey(row.sdkPackage, row.sdkMethod),
      methodKey(row.sdkMethod),
    ]) {
      let set = routesByKey.get(key);
      if (!set) {
        set = new Set();
        routesByKey.set(key, set);
      }
      set.add(routeSig(row));
      const kept = rowByKey.get(key);
      if (!kept || rowId(row) < rowId(kept)) rowByKey.set(key, row);
    }
  }
  // Register every tier only for unambiguous keys.
  for (const [key, routes] of routesByKey) {
    if (routes.size === 1) byKey.set(key, rowByKey.get(key)!);
  }

  return {
    lookup(call) {
      // Dynamic-dispatch calls (`performApiRequest('listResources')`) carry the
      // wrapper verb in `method` and the real SDK method name in `dispatchMethod`;
      // prefer the latter so the (class/package, method) tiers key off the SDK method.
      const method = call.dispatchMethod ?? call.method;
      if (!method) return undefined;
      // Candidate SDK identities on the call: the parsed `sdkName` (class name for
      // `kind:'sdk'`, package for some imported-sdk shapes) and the moniker package.
      const sdkName = call.sdkName;
      const monikerPkg = call.moniker?.packageName;
      if (sdkName) {
        const byClass = byKey.get(classKey(sdkName, method));
        if (byClass) return byClass;
        const byPkg = byKey.get(pkgKey(sdkName, method));
        if (byPkg) return byPkg;
      }
      if (monikerPkg) {
        const byPkg = byKey.get(pkgKey(monikerPkg, method));
        if (byPkg) return byPkg;
      }
      // Tier 3: unambiguous method-only match — recovers local clients whose
      // sdkName matched neither class nor package.
      const byMethod = byKey.get(methodKey(method));
      if (byMethod) return byMethod;
      return undefined;
    },
  };
}

/**
 * Synthesize the SDK method's egress as an `ExternalCallTarget` from a matched
 * sdkMapping row, so the existing protocol hop can match it against a downstream
 * entrypoint exactly as it would a direct call. Carries the row's `targetService`
 * as the service hint (translated to a repo by the chain-walker's serviceRepoMap).
 */
export function sdkMappingToDescriptor(row: SdkMapping): ExternalCallTarget {
  // Guarded by buildSdkMappingIndex (rows without http are not indexed), but keep
  // the type total for direct callers.
  const http = row.http;
  if (!http) throw new Error(`sdkMapping ${row.sdkClass}.${row.sdkMethod} has no http route`);
  return {
    protocol: 'http',
    http: { method: http.method, pathTemplate: http.pathTemplate },
    targetService: row.targetService,
  };
}
