import { useEffect, useId, useState } from 'react';
import mermaid from 'mermaid';
import { DiagramContainer } from './DiagramContainer';
import { AlertTriangle } from 'lucide-react';

interface MermaidDiagramProps {
  chart: string;
  zoomable?: boolean;
  maxHeight?: number;
  className?: string;
}

function initializeMermaid(isDark: boolean) {
  mermaid.initialize({
    startOnLoad: false,
    theme: isDark ? 'dark' : 'default',
    securityLevel: 'loose',
    fontFamily: "'SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', 'Fira Code', monospace",
    flowchart: {
      htmlLabels: true,
      curve: 'basis',
    },
  });
}

export function MermaidDiagram({ chart, zoomable = true, maxHeight = 500, className }: MermaidDiagramProps) {
  const id = useId().replace(/:/g, '_');
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Detect dark mode
  const isDark = typeof document !== 'undefined' && document.documentElement.classList.contains('dark');

  useEffect(() => {
    let mounted = true;

    async function renderDiagram() {
      try {
        // Initialize or reinitialize mermaid with current theme
        initializeMermaid(isDark);

        // Render the diagram
        const { svg: renderedSvg } = await mermaid.render(`mermaid-${id}`, chart);

        if (mounted) {
          setSvg(renderedSvg);
          setError(null);
        }
      } catch (err) {
        if (mounted) {
          setError(err instanceof Error ? err.message : 'Failed to render diagram');
          setSvg(null);
        }
      }
    }

    renderDiagram();

    return () => {
      mounted = false;
    };
  }, [chart, id, isDark]);

  // Error state
  if (error) {
    return (
      <div className={`rounded-lg border border-destructive/50 bg-bg-warning/10 p-4 ${className || ''}`}>
        <div className="flex items-start gap-2 text-content-warning">
          <AlertTriangle className="size-4 mt-0.5 shrink-0" />
          <div>
            <p className="font-medium text-sm">Failed to render Mermaid diagram</p>
            <pre className="text-xs mt-2 whitespace-pre-wrap opacity-80">{error}</pre>
            <details className="mt-2">
              <summary className="text-xs cursor-pointer hover:underline">Show source</summary>
              <pre className="text-xs mt-1 p-2 bg-bg-warning/10 rounded overflow-auto">{chart}</pre>
            </details>
          </div>
        </div>
      </div>
    );
  }

  // Loading state
  if (!svg) {
    return (
      <div
        className={`rounded-lg border bg-muted/30 p-4 flex items-center justify-center min-h-[100px] ${className || ''}`}
      >
        <div className="text-muted-foreground text-sm">Rendering diagram...</div>
      </div>
    );
  }

  // Render the diagram
  // Note: SVG is generated by mermaid library's render() function, which sanitizes the output
  const diagramContent = <div className="mermaid-svg-container" dangerouslySetInnerHTML={{ __html: svg }} />;

  if (zoomable) {
    return (
      <DiagramContainer maxHeight={maxHeight} className={className}>
        {diagramContent}
      </DiagramContainer>
    );
  }

  return (
    <div className={`rounded-lg border bg-muted/30 p-4 overflow-auto ${className || ''}`} style={{ maxHeight }}>
      {diagramContent}
    </div>
  );
}
