/**
 * CLI Alias Manager
 *
 * Installs a `coredoc` launcher on the user's PATH so they can run any CLI
 * subcommand (e.g. `coredoc mapper validate ...`) from the terminal without
 * having Node installed and without the desktop UI being open.
 *
 * The launcher invokes the same JS entry the desktop already spawns
 * (`dist/runtime/packages/cli/dist/index.js`) through Electron's bundled Node
 * via `ELECTRON_RUN_AS_NODE=1`. Same code path, same native bindings, no
 * external Node runtime required. Pattern matches VS Code's `code` command.
 *
 * Install paths:
 *   - macOS:   /usr/local/bin/coredoc          (admin prompt via osascript)
 *   - Linux:   $HOME/.local/bin/coredoc        (no privilege escalation)
 *   - Windows: %LOCALAPPDATA%\Coredoc\bin\coredoc.cmd
 *              + user PATH entry via `setx` on HKCU\Environment.
 *
 * On Linux AppImage the launcher must point at the integrated .AppImage file
 * (the mounted runtime binary disappears when the app exits); we read
 * `process.env.APPIMAGE` to discover it.
 */

import { app, type IpcMain } from 'electron';
import { execFile, type ExecFileException } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { promisify } from 'util';
import { IpcChannels, type CliAliasResult, type CliAliasStatus } from '../shared/ipc-types.js';
import { getCliPath } from './runtime-paths.js';
import { getConfiguredServerUrl } from './server-api.js';

const execFileAsync = promisify(execFile);

const LAUNCHER_BASENAME = process.platform === 'win32' ? 'coredoc.cmd' : 'coredoc';

// Marker line lets us tell our launcher apart from an unrelated file the user
// may have at the same path. Bumped only when the launcher format changes.
const LAUNCHER_MARKER = '# coredoc-desktop-launcher v1';

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------

function getInstallDir(): string {
  if (process.platform === 'win32') {
    const base = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local');
    return path.join(base, 'Coredoc', 'bin');
  }
  if (process.platform === 'darwin') {
    return '/usr/local/bin';
  }
  return path.join(os.homedir(), '.local', 'bin');
}

function getInstallPath(): string {
  return path.join(getInstallDir(), LAUNCHER_BASENAME);
}

/**
 * Path the launcher should exec — Electron's binary, except on Linux AppImage
 * where the mounted binary is ephemeral and we need the .AppImage file itself.
 *
 * `process.execPath` (not `app.execPath`) is the standard Node.js property and
 * is what Electron's main process exposes — in packaged mode it points at the
 * app binary (e.g. /Applications/Coredoc.app/Contents/MacOS/Coredoc).
 */
function getElectronExecPath(): string {
  if (process.platform === 'linux' && process.env.APPIMAGE) {
    return process.env.APPIMAGE;
  }
  return process.execPath;
}

function isPathOnEnvPath(targetDir: string): boolean {
  const envPath = process.env.PATH ?? '';
  const sep = process.platform === 'win32' ? ';' : ':';
  const norm = (p: string) => (process.platform === 'win32' ? p.replace(/\\/g, '/').toLowerCase() : p);
  const target = norm(targetDir);
  return envPath
    .split(sep)
    .map((p) => norm(p))
    .includes(target);
}

// ---------------------------------------------------------------------------
// Launcher script generation
// ---------------------------------------------------------------------------

/** Quote a path for inclusion in a POSIX sh single-quoted string. */
function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function buildPosixLauncher(electronExec: string, cliEntry: string, serverUrl: string): string {
  return [
    '#!/bin/sh',
    LAUNCHER_MARKER,
    '# Generated by the Coredoc desktop app. Do not edit by hand.',
    'export ELECTRON_RUN_AS_NODE=1',
    `export COREDOC_SERVER_URL=\${COREDOC_SERVER_URL:-${shSingleQuote(serverUrl)}}`,
    `exec ${shSingleQuote(electronExec)} ${shSingleQuote(cliEntry)} "$@"`,
    '',
  ].join('\n');
}

function buildWindowsLauncher(electronExec: string, cliEntry: string, serverUrl: string): string {
  // .cmd quoting: wrap each path in double-quotes; %* forwards args verbatim.
  return [
    '@echo off',
    `rem ${LAUNCHER_MARKER}`,
    'rem Generated by the Coredoc desktop app. Do not edit by hand.',
    'set "ELECTRON_RUN_AS_NODE=1"',
    `if not defined COREDOC_SERVER_URL set "COREDOC_SERVER_URL=${serverUrl}"`,
    `"${electronExec}" "${cliEntry}" %*`,
    '',
  ].join('\r\n');
}

function buildLauncher(electronExec: string, cliEntry: string, serverUrl: string): string {
  return process.platform === 'win32'
    ? buildWindowsLauncher(electronExec, cliEntry, serverUrl)
    : buildPosixLauncher(electronExec, cliEntry, serverUrl);
}

// ---------------------------------------------------------------------------
// Status
// ---------------------------------------------------------------------------

function describeUnsupported(): string | null {
  if (process.platform === 'linux' && !process.env.APPIMAGE && app.isPackaged) {
    // We only ship AppImage on Linux; if APPIMAGE isn't set the binary is
    // running from an extraction that won't exist after the app exits.
    return 'Run Coredoc from the .AppImage file (or integrate it with AppImageLauncher) before installing the terminal command.';
  }
  return null;
}

function buildHint(): string | undefined {
  if (process.platform === 'darwin') {
    return 'Installing to /usr/local/bin requires an admin password.';
  }
  if (process.platform === 'win32') {
    return 'Open a new terminal after installing for the PATH update to apply.';
  }
  return undefined;
}

/**
 * Whether a launcher is on disk. Exported because the launcher bakes
 * COREDOC_SERVER_URL in at install time: whoever changes the server has to know
 * that an installed launcher is now stale.
 */
export function isCliAliasInstalled(): boolean {
  return fs.existsSync(getInstallPath());
}

function getStatus(): CliAliasStatus {
  const installPath = getInstallPath();
  const installDir = getInstallDir();
  return {
    installed: fs.existsSync(installPath),
    path: installPath,
    inPath: isPathOnEnvPath(installDir),
    hint: buildHint(),
    unsupportedReason: describeUnsupported() ?? undefined,
  };
}

// ---------------------------------------------------------------------------
// Install / uninstall
// ---------------------------------------------------------------------------

function writeStagedLauncher(content: string): string {
  const stagedPath = path.join(os.tmpdir(), `coredoc-launcher-${process.pid}-${Date.now()}`);
  fs.writeFileSync(stagedPath, content, { mode: 0o755 });
  return stagedPath;
}

/** Move-into-place on macOS with admin prompt; rejects if user cancels. */
async function installWithAdminPrompt(stagedPath: string, destPath: string): Promise<void> {
  const destDir = path.dirname(destPath);
  // mkdir -p, then move, then chown to root:wheel and chmod 755 — matches
  // what `install(1)` would do but avoids depending on its flags.
  const script = [
    `/bin/mkdir -p ${shSingleQuote(destDir)}`,
    `/bin/mv ${shSingleQuote(stagedPath)} ${shSingleQuote(destPath)}`,
    `/bin/chmod 755 ${shSingleQuote(destPath)}`,
  ].join(' && ');
  // osascript-friendly: escape double-quotes for the wrapping AppleScript.
  const appleScript = `do shell script "${script.replace(/"/g, '\\"')}" with administrator privileges`;
  await execFileAsync('/usr/bin/osascript', ['-e', appleScript]);
}

async function uninstallWithAdminPrompt(destPath: string): Promise<void> {
  const script = `/bin/rm -f ${shSingleQuote(destPath)}`;
  const appleScript = `do shell script "${script.replace(/"/g, '\\"')}" with administrator privileges`;
  await execFileAsync('/usr/bin/osascript', ['-e', appleScript]);
}

/** Ensure the launcher dir is on the current user's PATH (HKCU\Environment). */
async function ensureWindowsPath(dir: string): Promise<boolean> {
  // Read current user PATH via `reg query`. Falls back to empty if not set.
  let currentUserPath = '';
  try {
    const { stdout } = await execFileAsync('reg', ['query', 'HKCU\\Environment', '/v', 'Path']);
    // Output: "    Path    REG_EXPAND_SZ    C:\\foo;C:\\bar"
    const match = stdout.match(/Path\s+REG_(?:EXPAND_)?SZ\s+(.+)/i);
    if (match) currentUserPath = match[1].trim();
  } catch {
    // Key/value missing — treat as empty.
  }

  const segments = currentUserPath.split(';').filter(Boolean);
  if (segments.some((seg) => seg.toLowerCase() === dir.toLowerCase())) {
    return false;
  }

  const next = segments.length > 0 ? `${currentUserPath};${dir}` : dir;
  // `setx` writes to HKCU\Environment and broadcasts WM_SETTINGCHANGE, which is
  // exactly what we want for new shells to see the change. It does NOT update
  // the current process's PATH (acceptable — the alias is for terminal use).
  await execFileAsync('setx', ['Path', next]);
  return true;
}

async function removeWindowsPath(dir: string): Promise<void> {
  let currentUserPath = '';
  try {
    const { stdout } = await execFileAsync('reg', ['query', 'HKCU\\Environment', '/v', 'Path']);
    const match = stdout.match(/Path\s+REG_(?:EXPAND_)?SZ\s+(.+)/i);
    if (match) currentUserPath = match[1].trim();
  } catch {
    return;
  }
  const filtered = currentUserPath.split(';').filter((seg) => seg && seg.toLowerCase() !== dir.toLowerCase());
  if (filtered.length === currentUserPath.split(';').filter(Boolean).length) {
    return; // dir wasn't on PATH, nothing to do
  }
  await execFileAsync('setx', ['Path', filtered.join(';')]);
}

async function install(): Promise<CliAliasResult> {
  const unsupported = describeUnsupported();
  if (unsupported) {
    return { success: false, status: getStatus(), error: unsupported };
  }

  const cliEntry = getCliPath();
  if (!cliEntry) {
    return {
      success: false,
      status: getStatus(),
      error: 'Bundled CLI not found inside the app. Reinstall Coredoc.',
    };
  }
  const electronExec = getElectronExecPath();
  if (!fs.existsSync(electronExec)) {
    return {
      success: false,
      status: getStatus(),
      error: `Coredoc binary not found at ${electronExec}.`,
    };
  }

  const launcher = buildLauncher(electronExec, cliEntry, getConfiguredServerUrl());
  const installPath = getInstallPath();
  const installDir = getInstallDir();

  try {
    if (process.platform === 'darwin') {
      const staged = writeStagedLauncher(launcher);
      try {
        await installWithAdminPrompt(staged, installPath);
      } finally {
        // Best-effort: if mv succeeded the staged file is gone; if it failed,
        // clean it up so we don't leave noise in /tmp.
        if (fs.existsSync(staged)) fs.unlinkSync(staged);
      }
    } else {
      fs.mkdirSync(installDir, { recursive: true });
      fs.writeFileSync(installPath, launcher, { mode: 0o755 });
    }
  } catch (err) {
    return {
      success: false,
      status: getStatus(),
      error: formatError(err),
    };
  }

  let note: string | undefined;
  if (process.platform === 'win32') {
    try {
      const changed = await ensureWindowsPath(installDir);
      if (changed) {
        note = 'Open a new terminal for the PATH update to take effect.';
      }
    } catch (err) {
      // Launcher is on disk but PATH wasn't updated — partial success worth reporting.
      return {
        success: false,
        status: getStatus(),
        error: `Launcher installed at ${installPath} but PATH update failed: ${formatError(err)}`,
      };
    }
  } else if (!isPathOnEnvPath(installDir)) {
    note = `${installDir} is not on your PATH. Add it to your shell profile to use the \`coredoc\` command.`;
  }

  return { success: true, status: getStatus(), note };
}

async function uninstall(): Promise<CliAliasResult> {
  const installPath = getInstallPath();
  const installDir = getInstallDir();

  if (!fs.existsSync(installPath)) {
    return { success: true, status: getStatus() };
  }

  try {
    if (process.platform === 'darwin') {
      await uninstallWithAdminPrompt(installPath);
    } else {
      fs.unlinkSync(installPath);
    }
  } catch (err) {
    return { success: false, status: getStatus(), error: formatError(err) };
  }

  if (process.platform === 'win32') {
    try {
      await removeWindowsPath(installDir);
    } catch {
      // Non-fatal: launcher is gone, PATH cleanup is cosmetic.
    }
  }

  return { success: true, status: getStatus() };
}

function formatError(err: unknown): string {
  if (err instanceof Error) {
    // osascript prints "User canceled." (code 1) when the admin dialog is dismissed.
    const e = err as ExecFileException & { stderr?: string };
    if (e.stderr && /User canceled/i.test(e.stderr)) {
      return 'Cancelled by user.';
    }
    return err.message;
  }
  return String(err);
}

// ---------------------------------------------------------------------------
// IPC wiring
// ---------------------------------------------------------------------------

export function registerCliAliasHandlers(ipcMain: IpcMain): void {
  ipcMain.handle(IpcChannels.CLI_ALIAS_GET_STATUS, () => getStatus());
  ipcMain.handle(IpcChannels.CLI_ALIAS_INSTALL, () => install());
  ipcMain.handle(IpcChannels.CLI_ALIAS_UNINSTALL, () => uninstall());
}
